
on:
  push:
    branches: [ main ]
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Auto Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v1.0.1
        
    - name: FTP Deploy
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        ftp-server: ${{ secrets.PERIKANAN_SERVER }}
        ftp-username: ${{ secrets.PERIKANAN_USERNAME }}
        ftp-password: ${{ secrets.PERIKANAN_PASSWORD }}
        protocol: ftps
        port: ${{ secrets.PERIKANAN_PORT }}
        exclude: .git*
          - .git*/**
          - .github
